import { http } from "./http";
import { PredictorError } from "./errors";
import { OnnxPredictor, loadModel } from "./onnx/OnnxPredictor";
import { listPipelines, startTraining, trainModel, waitForModel, getModel, listModels } from "./training";

const UPLOAD_INTERVAL = 5 * 1000;

const URLS = {
  initDatasetIncrement: "/api/v1/deviceapi/dataset/init/",
  addDatasetIncrement: "/api/v1/deviceapi/dataset/append/"
};

/**
 * Uploads a whole dataset to a specific project
 * @param {string} url - The url of the backend server
 * @param {string} key - The Device-Api-Key (write access)
 * @param {{ name: string, timeSeries: { name: string, data: [number, number][] }[], metaData?: { [key: string]: string }, labeling?: string }} dataset
 *   time-series data as [unix ms, value] pairs; labeling as "{labeling}_{label}" for the whole dataset
 * @returns {Promise<string>} The id of the created dataset
 */
async function sendDataset(url, key, dataset) {
  if (!dataset || !dataset.name || !Array.isArray(dataset.timeSeries)) {
    throw new Error("dataset needs a name and a timeSeries array");
  }
  const init = await http.post(url, URLS.initDatasetIncrement + key, {
    name: dataset.name,
    metaData: dataset.metaData || {},
    timeSeries: dataset.timeSeries.map((ts) => ts.name),
  });
  if (!init || !init.id) {
    throw new Error("Could not create dataset");
  }
  let labeling = undefined;
  if (dataset.labeling) {
    const [labelingName, labelName] = dataset.labeling.split("_");
    labeling = { labelingName, labelName };
  }
  await http.post(url, URLS.addDatasetIncrement + key + "/" + init.id, {
    data: dataset.timeSeries.map((ts) => ({ name: ts.name, data: ts.data })),
    labeling: labeling,
  });
  return init.id;
}

/**
 *
 * @param {string} url - The url of the backend server
 * @param {string} key - The Device-Api-Key
 * @param {boolean} useDeviceTime - True if you want to use timestamps generated by the server
 * @returns Function to upload single datapoints to one dataset inside a specific project
 */
async function datasetCollector(
  url,
  key,
  name,
  useDeviceTime,
  timeSeries,
  metaData,
  datasetLabel
) {
  var labeling = undefined;
  if (datasetLabel) {
    labeling = {"labelingName": datasetLabel.split("_")[0], "labelName": datasetLabel.split("_")[1]}
  }

  const data = await http.post(url, URLS.initDatasetIncrement + key, {
    name: name,
    metaData: metaData,
    timeSeries: timeSeries,
    labeling: labeling
  });
  if (!data || !data.id) {
    throw new Error("Could not generate datasetCollector");
  }
  const datasetKey = data.id;

  var uploadComplete = false;
  var dataStore = { data: [] };
  var lastChecked = Date.now()
  var error = undefined;
  var timeSeries = timeSeries;

  /**
   * Uploads a vlaue for a specific timestamp to a datasets timeSeries with name sensorName
   * @param {string} name - The name of the timeSeries to upload the value to
   * @param {number} value - The datapoint to upload
   * @param {number} time - The timestamp assigned to the datapoint
   * @returns A Promise indicating success or failure of upload
   */
  function addDataPoint(time, name, value) {

    if (!timeSeries.includes(name)) {
      throw Error("invalid time-series name")
    }

    if (error) {
      throw new Error(error);
    }
    if (typeof value !== "number") {
      throw new Error("Datapoint is not a number");
    }
    if (!useDeviceTime && typeof time !== "number") {
      throw new Error("Provide a valid timestamp");
    }

    if (useDeviceTime) {
      time = new Date().getTime();
    }

    value = Math.round(value * 100) / 100;

    if (dataStore.data.every((elm) => elm.name !== name)) {
      dataStore.data.push({
        name: name,
        data: [[time, value]],
      });
    } else {
      const idx = dataStore.data.findIndex(
        (elm) => elm.name === name
      );
      dataStore.data[idx].data.push([time, value]);

      if (dataStore.data[idx].start > time) {
        dataStore.data[idx].start = time;
      }
      if (dataStore.data[idx].end < time) {
        dataStore.data[idx].end = time;
      }
    }

    if (Date.now() - lastChecked > UPLOAD_INTERVAL) {
      // background upload: a failure is reported by the next addDataPoint / onComplete
      upload().catch((e) => {
        error = e.message;
      });
      lastChecked = Date.now();
      dataStore = { data: [] };
    }
  }

  async function upload(uploadLabel) {
    const tmp_datastore = JSON.parse(JSON.stringify(dataStore));
    await http.post(url, URLS.addDatasetIncrement + key + "/" + datasetKey, {"data": tmp_datastore.data, "labeling": uploadLabel});
  }

  /**
   * Synchronizes the server with the data when you have added all data
   */
  async function onComplete() {
    if (uploadComplete) {
      throw new Error("Dataset is already uploaded");
    }
    await upload(labeling);
    if (error) {
      throw new Error(error);
    }
    uploadComplete = true;
  }

  if (useDeviceTime) {
    return {
      addDataPoint: (sensorName, value) =>
        addDataPoint(undefined, sensorName, value),
      onComplete: onComplete,
    };
  } else {
    return {
      addDataPoint: (time, sensorName, value) =>
        addDataPoint(time, sensorName, value),
      onComplete: onComplete,
    };
  }
}

const edgeML = {
  // data collection
  datasetCollector: datasetCollector,
  sendDataset: sendDataset,
  // training on the edge-ml server
  listPipelines: listPipelines,
  trainModel: trainModel,
  startTraining: startTraining,
  waitForModel: waitForModel,
  getModel: getModel,
  listModels: listModels,
  // inference
  loadModel: loadModel,
  OnnxPredictor: OnnxPredictor,
  PredictorError: PredictorError,
};

export default edgeML;
export {
  datasetCollector,
  sendDataset,
  listPipelines,
  trainModel,
  startTraining,
  waitForModel,
  getModel,
  listModels,
  loadModel,
  OnnxPredictor,
  PredictorError,
};
